import os

TELEGRAM_TOKEN = os.getenv("TELEGRAM_TOKEN")
TELEGRAM_CHAT_ID = int(os.getenv("TELEGRAM_CHAT_ID"))

BINANCE_API_KEY = os.getenv("BINANCE_API_KEY")
BINANCE_SECRET = os.getenv("BINANCE_SECRET")

FUNDING_THRESHOLD = float(os.getenv("FUNDING_THRESHOLD", -0.0005))
SCAN_INTERVAL_SEC = int(os.getenv("SCAN_INTERVAL_SEC", 120))